const express = require("express");
const { sendOtp } = require("./../controllers/auth/register/sendOtp.js");
const { verifyOtp } = require("./../controllers/auth/register/verifyOtp.js");
const { resendOtp } = require("./../controllers/auth/register/resendOtp.js");
const { login } = require("../controllers/auth/login.js");
const { logout } = require("../controllers/auth/logout.js");
const { createVaultPin } = require("../controllers/auth/createVaultPin.js");
const { vaultAuth } = require("../controllers/auth/vaultAuth.js");
const { auth, isAuthUser } = require("./../middleware/auth.js");
const { profile } = require("./../controllers/auth/profile.js");
const router = express.Router();

router.post("/register/sendOtp", sendOtp);
router.post("/register/verifyOtp", verifyOtp);
router.post("/register/resendOtp", resendOtp);
router.post("/login", login);
router.post("/logout", logout);
router.post("/createVaultPin", auth,isAuthUser, vaultAuth, createVaultPin);
router.post("/vaultAuth", auth, isAuthUser, vaultAuth);
router.post("/profile", auth, isAuthUser, profile);
module.exports = router;
